ProjetoAutomotivo/ProjetoAutomotivo/Models/ErrorViewModel.cs
namespace ProjetoAutomotivo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjetoAutomotivo/ProjetoAutomotivo/Models/Marca.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgenciaAutomotiva.Models
{
    public class Marca
    {
        public List<MarcaModel> marcas = new List<MarcaModel>();

        public Marca()
        {
            marcas.Add(new MarcaModel(1, "Volkswagen", MarcaModel.Status.Ativo));
            marcas.Add(new MarcaModel(2, "Renault", MarcaModel.Status.Ativo));
            marcas.Add(new MarcaModel(3, "Ford", MarcaModel.Status.Ativo));
        }

        public void adicionarMarca(MarcaModel marca)
        {
            marcas.Add(marca);
        }

        public void atualizarMarca(MarcaModel marca)
        {
            marcas.RemoveAt(marcas.FindIndex(m => m.id == marca.id));
            marcas.Add(marca);
        }

        public MarcaModel getMarca(int id)
        {
            return marcas.FindLast(m => m.id == id);
        }

        public void excluirMarca(int id)
        {
            MarcaModel marca = new MarcaModel
            (
                marcas.FindLast(m => m.id == id).id,
                marcas.FindLast(m => m.id == id).nome,
                MarcaModel.Status.Cancelado
            );
            marcas.RemoveAt(marcas.FindIndex(m => m.id == id));
            marcas.Add(marca);
        }

    }
}

ProjetoAutomotivo/ProjetoAutomotivo/Models/MarcaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgenciaAutomotiva.Models
{
    public class MarcaModel
    {
        public int id { get; private set; }
        public string nome { get; private set; }
        public Status status { get; private set; }

        public MarcaModel(int id, string nome, Status status)
        {
            this.id = id;
            this.nome = nome;
            this.status = status;
        }

        public enum Status
        {
            Ativo = 1,
            Cancelado = 0
        }
    }
}

ProjetoAutomotivo/ProjetoAutomotivo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoAutomotivo.Models;
using System.Diagnostics;

namespace ProjetoAutomotivo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetoAutomotivo/ProjetoAutomotivo/Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AgenciaAutomotiva.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AgenciaAutomotiva.Controllers
{
    public class MarcaController : Controller
    {
        private static Marca _marca = new Marca();

        // GET: Marca
        public ActionResult Index()
        {
            return View(_marca.marcas);
        }

        // GET: Marca/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Marca/Criar
        public ActionResult Criar()
        {
            return View();
        }

        // POST: Marca/Criar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(IFormCollection collection)
        {
            try
            {
                MarcaModel marca = new MarcaModel
                (
                    Convert.ToInt32(collection["id"]),
                    collection["nome"].ToString(),
                    (MarcaModel.Status)Enum.Parse(typeof(MarcaModel.Status), collection["status"], true)
                );

                _marca.adicionarMarca(marca);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Marca/Editar/5
        public ActionResult Editar(int id)
        {
            return View(_marca.getMarca(id));
        }

        // POST: Marca/Editar/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(IFormCollection collection)
        {
            try
            {
                MarcaModel marca = new MarcaModel
                (
                    Convert.ToInt32(collection["id"]),
                    collection["nome"].ToString(),
                    (MarcaModel.Status)Enum.Parse(typeof(MarcaModel.Status), collection["status"], true)
                );

                _marca.atualizarMarca(marca);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Marca/Excluir/5
        public ActionResult Excluir(int id)
        {
            //_marca.excluirMarca(id);
            return View(_marca.getMarca(id));
        }

        // POST: Marca/Excluir/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Excluir(int id, IFormCollection collection)
        {
            try
            {
                _marca.excluirMarca(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjetoAutomotivo/ProjetoAutomotivo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjetoAutomotivo/ProjetoAutomotivo/Views/Marca/Criar.cshtml
@model AgenciaAutomotiva.Models.MarcaModel

@{
    ViewData["Title"] = "Criar";
}

<h1>Criar</h1>

<h4>MarcaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Criar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="id" class="control-label"></label>
                <input asp-for="id" class="form-control" />
                <span asp-validation-for="id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="status" class="control-label"></label>
                <input asp-for="status" class="form-control" />
                <span asp-validation-for="status" class="text-danger"></span>
                <select asp-for="@Model.status" asp-items="@Html.GetEnumSelectList<>()" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetoAutomotivo/ProjetoAutomotivo/Views/Marca/Editar.cshtml
@model AgenciaAutomotiva.Models.MarcaModel

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>MarcaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="id" class="control-label"></label>
                <input asp-for="id" class="form-control" />
                <span asp-validation-for="id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="status" class="control-label"></label>
                <input asp-for="status" class="form-control" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetoAutomotivo/ProjetoAutomotivo/Views/Marca/Excluir.cshtml
@model AgenciaAutomotiva.Models.MarcaModel

@{
    ViewData["Title"] = "Excluir";
}

<h1>Excluir</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MarcaModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.status)
        </dd>
    </dl>
    
    <form asp-action="Excluir">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjetoAutomotivo/ProjetoAutomotivo/Views/Marca/Index.cshtml
@model IEnumerable<AgenciaAutomotiva.Models.MarcaModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Cadastro de marcas</h1>

<p>
    <a class="btn btn-primary" asp-action="Criar">Adicionar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new {  id= item.id }) |
                @Html.ActionLink("Excluir", "Excluir", new { id= item.id  })
            </td>
        </tr>
    }
    </tbody>
</table>

ProjetoAutomotivo/ProjetoAutomotivo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoAutomotivo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoAutomotivo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projeto Automotivo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marca" asp-action="Index">Marca</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProjetoAutomotivo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>